export const OFFICE_ALIASES = Object.freeze({
  venerable: 'venerable', maestru_venerabil: 'venerable',
  first_warden: 'first_warden', prim_supraveghetor: 'first_warden', s1: 'first_warden',
  second_warden: 'second_warden', al_doilea_supraveghetor: 'second_warden', s2: 'second_warden',
  orator: 'orator',
  secretary: 'secretary', secretar: 'secretary',
  treasurer: 'treasurer', trezorier: 'treasurer',
  hospitalier: 'hospitalier', ospitalier: 'hospitalier',
  expert: 'expert',
  master_of_ceremonies: 'master_of_ceremonies', maestru_de_ceremonii: 'master_of_ceremonies',
  tyler: 'tyler', acoperitor: 'tyler',
  librarian: 'librarian', bibliotecar: 'librarian',
  mentor: 'mentor',
});

export const OFFICER_CATALOG = Object.freeze([
  {
    code: 'venerable', label: 'Maestru Venerabil', minGrade: 3, position: { zone: 'orient_center', x: 0, y: 0.42, z: 0.92 },
    jewel: 'Echer', responsibility: 'coordonează, convoacă, moderează și urmărește respectarea cadrului Loji',
    interaction: { label: 'Conducerea Lojei', route: '/registru', capabilities: ['governance_overview', 'office_terms', 'audit_summary'] },
    sourceRefIds: ['ritual-apprentice-2012', 'regulation-general-6016', 'leadership-keys-hermeneutics', 'statute-mlnr-2003-historical'],
    validation: { required: true, reason: 'Digital capabilities remain subject to the configured permission matrix.' },
  },
  {
    code: 'first_warden', label: 'Primul Supraveghetor', minGrade: 3, position: { zone: 'occident_north', x: -0.48, y: 0.24, z: -0.82 },
    jewel: 'Nivela', responsibility: 'îndrumă lucrul Calfelor și susține ordinea Coloanei',
    interaction: { label: 'Parcursul Calfei', route: '/biblioteca', capabilities: ['grade_two_path', 'learning_review'] },
    sourceRefIds: ['ritual-apprentice-2012', 'regulation-general-6016', 'leadership-keys-hermeneutics'],
    validation: { required: true, reason: 'Office code must be configured in tenant governance before activation.' },
  },
  {
    code: 'second_warden', label: 'Al Doilea Supraveghetor', minGrade: 3, position: { zone: 'south_center', x: 0.78, y: 0.14, z: 0 },
    jewel: 'Perpendiculara', responsibility: 'îndrumă lucrul Ucenicilor și susține ordinea Coloanei',
    interaction: { label: 'Parcursul Ucenicului', route: '/biblioteca', capabilities: ['grade_one_path', 'learning_review'] },
    sourceRefIds: ['ritual-apprentice-2012', 'regulation-general-6016', 'leadership-keys-hermeneutics'],
    validation: { required: true, reason: 'Office code must be configured in tenant governance before activation.' },
  },
  {
    code: 'orator', label: 'Orator', minGrade: 3, position: { zone: 'orient_south', x: 0.56, y: 0.28, z: 0.82 },
    jewel: 'Cartea deschisă', responsibility: 'urmărește legalitatea, formulează concluzii și contribuie la validarea documentelor',
    interaction: { label: 'Legalitate și concluzii', route: '/registru', capabilities: ['compliance_review', 'decision_conclusions'] },
    sourceRefIds: ['ritual-apprentice-2012', 'regulation-general-6016'],
    validation: { required: true, reason: 'Requires a dedicated tenant office definition and server-side permissions.' },
  },
  {
    code: 'secretary', label: 'Secretar', minGrade: 3, position: { zone: 'orient_north', x: -0.56, y: 0.28, z: 0.82 },
    jewel: 'Pene încrucișate', responsibility: 'matricol, dosare, convocări, prezențe, planșe, corespondență și arhivă',
    interaction: { label: 'Arhiva Vie', route: '/dosare-frati', capabilities: ['brother_dossiers', 'matricol', 'convocations', 'attendance', 'visitor_records', 'documents'] },
    sourceRefIds: ['ritual-apprentice-2012', 'regulation-general-6016', 'registry-csa-6025-6026', 'statute-mlnr-2003-historical'],
    validation: { required: true, reason: 'PII fields and import mappings require explicit tenant approval; never index them in public search.' },
  },
  {
    code: 'treasurer', label: 'Trezorier', minGrade: 3, position: { zone: 'south_at_east', x: 0.76, y: 0.08, z: 0.62 },
    jewel: 'Două chei încrucișate', responsibility: 'gestionează metalele, documentele justificative și raportarea financiară',
    interaction: { label: 'Camera Măsurii', route: '/metale', capabilities: ['accounts', 'budgets', 'contributions', 'payments', 'reports'] },
    sourceRefIds: ['ritual-apprentice-2012', 'regulation-general-6016', 'statute-mlnr-2003-historical'],
    validation: { required: true, reason: 'Financial actions require the configured approval workflow and audit.' },
  },
  {
    code: 'hospitalier', label: 'Ospitalier', minGrade: 3, position: { zone: 'north_at_east', x: -0.76, y: 0.08, z: 0.62 },
    jewel: 'Punga ospitalieră', responsibility: 'coordonează sprijinul discret și fondurile destinate ajutorării',
    interaction: { label: 'Vatra Fraternă', route: '/ospitalier', capabilities: ['support_cases', 'events', 'confidential_notes'] },
    sourceRefIds: ['ritual-apprentice-2012', 'regulation-general-6016', 'statute-nova-reperta-2024'],
    validation: { required: true, reason: 'Case data is confidential and must remain office-scoped and audited.' },
  },
  {
    code: 'expert', label: 'Expert', minGrade: 3, position: { zone: 'north_east_inner', x: -0.58, y: 0.06, z: 0.56 },
    jewel: 'Spada, rigla și ochiul', responsibility: 'siguranță, verificarea vizitatorilor și instruire ritualică și ezoterică',
    interaction: { label: 'Atelierul de instruire', route: '/biblioteca', capabilities: ['ritual_readiness', 'visitor_verification', 'symbol_review'] },
    sourceRefIds: ['ritual-apprentice-2012', 'regulation-general-6016', 'guide-meetings-6019', 'leadership-keys-hermeneutics'],
    validation: { required: true, reason: 'Never digitize recognition tests or arcane responses in the client.' },
  },
  {
    code: 'master_of_ceremonies', label: 'Maestru de Ceremonii', minGrade: 3, position: { zone: 'occident_south_of_warden', x: 0.18, y: 0.05, z: -0.82 },
    jewel: 'Spadele și bastonul', responsibility: 'pregătește spațiul, coordonează intrările și susține desfășurarea ordonată',
    interaction: { label: 'Pregătirea Ținutei', route: '/', capabilities: ['event_checklist', 'room_readiness', 'protocol_plan'] },
    sourceRefIds: ['ritual-apprentice-2012', 'regulation-general-6016', 'guide-meetings-6019'],
    validation: { required: true, reason: 'Requires a dedicated tenant office definition and reviewed checklists.' },
  },
  {
    code: 'tyler', label: 'Acoperitor', minGrade: 3, position: { zone: 'inside_west_south', x: 0.5, y: 0.04, z: -0.94 },
    jewel: 'Spada verticală', responsibility: 'păstrează pragul interior conform rolului atribuit',
    interaction: { label: 'Starea pragului', route: '/', capabilities: ['entry_status'] },
    sourceRefIds: ['ritual-apprentice-2012', 'regulation-general-6016'],
    validation: { required: true, reason: 'Requires a dedicated tenant office definition; no real security decision is delegated to the 3D scene.' },
  },
  {
    code: 'librarian', label: 'Bibliotecar', minGrade: 3, position: { zone: 'library_annex', x: -0.86, y: 0.04, z: 0.12 },
    jewel: 'Semn platformă - carte și fir de legătură', responsibility: 'curatoria cărților, drepturilor, conceptelor și versiunilor',
    interaction: { label: 'Biblioteca Vie', route: '/biblioteca', capabilities: ['library_admin', 'concept_moderation', 'publication_review'] },
    sourceRefIds: ['regulation-general-6016', 'guide-meetings-6019', 'leadership-keys-hermeneutics'],
    validation: { required: true, reason: 'Platform office, not a ritual seat; tenant must approve its visual annex and mandate.' },
  },
  {
    code: 'mentor', label: 'Mentor', minGrade: 3, position: { zone: 'mentorship_annex', x: 0.86, y: 0.04, z: 0.12 },
    jewel: 'Semn platformă - lampă și cerc', responsibility: 'însoțește parcursuri educative fără a conferi grade sau drepturi',
    interaction: { label: 'Cercul mentoratului', route: '/concepte', capabilities: ['learning_feedback', 'debate_moderation', 'mentorship_paths'] },
    sourceRefIds: ['regulation-general-6016', 'leadership-keys-hermeneutics'],
    validation: { required: true, reason: 'Platform office; pedagogical scope requires tenant approval and audit.' },
  },
]);
