const sharedSpatialRules = Object.freeze({
  coordinateSystem: {
    x: 'Miazănoapte (-) către Miazăzi (+)',
    y: 'pardoseală către boltă',
    z: 'Occident (-) către Orient (+)',
    unit: 'normalized',
  },
  interactionLimits: {
    noRitualReenactment: true,
    noRecognitionData: true,
    noHiddenHigherDegreeAssets: true,
    reducedMotionFallback: 'dom_or_svg',
    mobileFrameRateCap: 30,
    mobileMaxDevicePixelRatio: 1.25,
  },
});

export const GRADE_SCENES = Object.freeze({
  1: {
    id: 'apprentice-threshold',
    grade: 1,
    title: 'Pragul Pietrei Brute',
    subtitle: 'Observă, păstrează tăcerea și începe lucrarea interioară.',
    educationalTheme: 'introspecție, verticalitate, atenție și transformare personală',
    atmosphere: {
      palette: ['#060810', '#0c1830', '#19345a', '#b9974f'],
      light: 'low_guided_light',
      particles: 'slow_dust_and_constellations',
      cameraStart: { x: -0.18, y: 1.62, z: -0.88, lookAt: { x: -0.12, y: 1.12, z: 0.35 } },
    },
    spatialRules: sharedSpatialRules,
    zones: [
      { id: 'reflection-room', label: 'Camera reflecției', position: { x: -0.72, y: 0, z: -0.72 }, interaction: 'guided_reflection' },
      { id: 'lost-steps-hall', label: 'Sala pregătirii', position: { x: 0, y: 0, z: -0.84 }, interaction: 'orientation_and_readiness' },
      { id: 'north-learning-column', label: 'Coloana observației', position: { x: -0.64, y: 0, z: 0.06 }, interaction: 'degree_one_learning' },
      { id: 'mosaic-center', label: 'Centrul simbolic', position: { x: 0, y: 0.02, z: 0.2 }, interaction: 'pattern_observation' },
      { id: 'east-light', label: 'Orientul', position: { x: 0, y: 0.3, z: 0.88 }, interaction: 'distant_orientation_only' },
    ],
    symbolIds: ['g1-rough-stone', 'g1-plumb-axis', 'g1-mosaic-floor', 'g1-three-pillars', 'g1-threshold-columns', 'g1-great-lights', 'g1-star-vault', 'g1-seasonal-circle'],
    sourceRefIds: ['ritual-apprentice-2012', 'constitution-mlnr-6016', 'guide-meetings-6019', 'ceremony-saint-john-summer-6024'],
    validation: { required: true, reason: 'Exact geometry, wording, textures and symbol visibility require authorized sign-off.' },
  },
  2: {
    id: 'fellowcraft-workshop',
    grade: 2,
    title: 'Atelierul Cunoașterii',
    subtitle: 'Măsoară, compară și descoperă ordinea dintre lucruri.',
    educationalTheme: 'simțuri, geometrie, științe, arte, discernământ și relaționare',
    atmosphere: {
      palette: ['#07101c', '#102c44', '#24526a', '#d0ad59'],
      light: 'measured_midday_rays',
      particles: 'geometric_points_and_orbits',
      cameraStart: { x: 0.32, y: 1.68, z: -0.62, lookAt: { x: 0.06, y: 1.18, z: 0.42 } },
    },
    spatialRules: sharedSpatialRules,
    zones: [
      { id: 'geometry-workbench', label: 'Masa geometriei', position: { x: 0.46, y: 0.12, z: 0.06 }, interaction: 'construct_and_compare' },
      { id: 'senses-gallery', label: 'Galeria percepției', position: { x: 0.7, y: 0.12, z: 0.42 }, interaction: 'five_senses_sequence' },
      { id: 'world-spheres', label: 'Orizonturile cunoașterii', position: { x: 0, y: 1.42, z: -0.52 }, interaction: 'paired_orbit_exploration' },
      { id: 'concept-constellation', label: 'Bolta conceptelor', position: { x: -0.28, y: 1.72, z: 0.28 }, interaction: 'connect_validated_concepts' },
      { id: 'fellowcraft-board', label: 'Planșa gradului', position: { x: 0, y: 0.02, z: 0.22 }, interaction: 'guided_symbol_map' },
    ],
    symbolIds: ['g2-cubic-stone', 'g2-level', 'g2-blazing-star', 'g2-paired-spheres', 'g2-five-senses', 'g2-great-lights', 'g2-tracing-board'],
    sourceRefIds: ['ritual-apprentice-2012', 'ritual-fellowcraft-2012', 'constitution-mlnr-6016', 'guide-meetings-6019'],
    validation: { required: true, reason: 'Grade 2 asset composition and explanations require authorized sign-off.' },
  },
  3: {
    id: 'master-middle-chamber',
    grade: 3,
    title: 'Camera Continuității',
    subtitle: 'Leagă experiența, responsabilitatea și transmiterea mai departe.',
    educationalTheme: 'adevăr, continuitate, memorie, cooperare, mentorat și responsabilitate',
    atmosphere: {
      palette: ['#05070d', '#111927', '#243047', '#b99345'],
      light: 'deep_contrast_with_recovered_light',
      particles: 'slow_acacia_points_and_memory_threads',
      cameraStart: { x: 0.05, y: 1.72, z: -0.5, lookAt: { x: 0, y: 1.08, z: 0.5 } },
    },
    spatialRules: sharedSpatialRules,
    zones: [
      { id: 'middle-chamber', label: 'Camera de Mijloc', position: { x: 0, y: 0, z: 0.44 }, interaction: 'continuity_reflection' },
      { id: 'memory-veil', label: 'Pragul memoriei', position: { x: 0, y: 0.82, z: 0.34 }, interaction: 'tradition_timeline' },
      { id: 'mentorship-circle', label: 'Cercul mentoratului', position: { x: -0.38, y: 0.06, z: 0.02 }, interaction: 'mentor_pathways' },
      { id: 'project-table', label: 'Masa lucrării comune', position: { x: 0.42, y: 0.12, z: 0.02 }, interaction: 'group_projects' },
      { id: 'master-board', label: 'Planșa gradului', position: { x: 0, y: 0.02, z: 0.2 }, interaction: 'guided_symbol_map' },
    ],
    symbolIds: ['g3-acacia', 'g3-circle-center', 'g3-great-lights', 'g3-memory-veil', 'g3-master-board', 'g3-travel-lines'],
    sourceRefIds: ['ritual-apprentice-2012', 'ritual-master-2012', 'constitution-mlnr-6016', 'guide-meetings-6019'],
    validation: { required: true, reason: 'Grade 3 symbolism must be reviewed without reproducing ceremonial or recognition content.' },
  },
});
