// Server-only source metadata. These documents are implementation references,
// not library content and not a source of client-visible ritual text.

export const SOURCE_HIERARCHY = Object.freeze([
  {
    rank: 1,
    key: 'active_degree_ritual',
    label: 'Ritualul activ al gradului',
    rule: 'Controls the degree-specific geometry, objects, positions and educational sequence.',
  },
  {
    rank: 2,
    key: 'constitution_and_regulation',
    label: 'Constituția și Regulamentul General în vigoare',
    rule: 'Controls governance, records, offices, eligibility, voting and administrative boundaries.',
  },
  {
    rank: 3,
    key: 'approved_guides_and_ceremonies',
    label: 'Ghiduri și ceremonii aprobate',
    rule: 'Clarifies approved event types, protocol, preparation and optional ceremonial configurations.',
  },
  {
    rank: 4,
    key: 'tenant_legal_and_operational_records',
    label: 'Acte și evidențe operaționale ale tenantului',
    rule: 'Controls the public-association boundary and the fields required by the local registry workflow.',
  },
  {
    rank: 5,
    key: 'internal_pedagogy',
    label: 'Materiale pedagogice interne',
    rule: 'May inform learning activities only after review by the responsible officers.',
  },
  {
    rank: 6,
    key: 'reference_and_historical',
    label: 'Lucrări de referință și documente istorice',
    rule: 'Context only; never overrides an active ritual, constitution, regulation or approved guide.',
  },
]);

export const SOURCE_REFS = Object.freeze([
  {
    id: 'ritual-apprentice-2012',
    document: '1-Ritualul Ucenicului - 2012.pdf',
    kind: 'private_ritual_specification',
    authorityTier: 'active_degree_ritual',
    locator: { pages: [118, 119, 120, 121, 122, 123, 124, 125, 129], sections: ['Anexa 2', 'Anexa 3', 'Anexa 5'] },
    use: 'Grade 1 scene, shared temple geometry, symbolic tools, officer positions and dialog-based instruction model.',
    review: { required: true, reason: 'Confirm edition applicability and exact visual interpretation with an authorized reviewer.' },
  },
  {
    id: 'ritual-fellowcraft-2012',
    document: '2-Ritualul Calfa - 2012-1_260713_171436.pdf',
    kind: 'private_ritual_specification',
    authorityTier: 'active_degree_ritual',
    locator: { pages: [61, 72, 73, 74, 75], sections: ['Descrierea Lojii', 'Instrucția gradului'] },
    use: 'Grade 2 differences, workshop symbols and a question-observation-application learning sequence.',
    review: { required: true, reason: 'Confirm edition applicability; arcane recognition data is intentionally excluded.' },
  },
  {
    id: 'ritual-master-2012',
    document: 'Ritualul Maestrului 2012 VERSIUNEA TIPAR FINAL-1_260713_171452.pdf',
    kind: 'private_ritual_specification',
    authorityTier: 'active_degree_ritual',
    locator: { pages: [69, 82, 83, 84, 85], sections: ['Descrierea Lojii', 'Instrucția gradului'] },
    use: 'Grade 3 scene differences and educational themes of continuity, truth, responsibility and transmission.',
    review: { required: true, reason: 'Confirm edition applicability; ceremonial reenactment and arcane data are intentionally excluded.' },
  },
  {
    id: 'regulation-general-6016',
    document: '01 Regulament final MLNR.pdf',
    kind: 'normative_governance',
    authorityTier: 'constitution_and_regulation',
    locator: { pages: [25, 26, 27, 28, 29, 39, 40, 41, 42, 43, 44, 45, 47, 48, 53], sections: ['Art. 12-13', 'Art. 16-17', 'Art. 21'] },
    use: 'Office duties, registry and archive duties, attendance, documents, visitor checks, deliberation and study obligations.',
    review: { required: true, reason: 'Legal/normative applicability must be confirmed before enforcing a workflow.' },
  },
  {
    id: 'constitution-mlnr-6016',
    document: 'Constitutia MLNR 2016 .docx',
    kind: 'normative_principles',
    authorityTier: 'constitution_and_regulation',
    locator: { sections: ['Preambul', 'Declarație de principii', 'Art. 2.3', 'Art. 3', 'Art. 8'] },
    use: 'Three-degree model, membership states, identity, regularity and ethical guardrails.',
    review: { required: true, reason: 'Confirm that the supplied edition is the applicable edition.' },
  },
  {
    id: 'guide-meetings-6019',
    document: 'Ghidul Tinutelor Masonice.pdf',
    kind: 'approved_guide',
    authorityTier: 'approved_guides_and_ceremonies',
    locator: { pages: [4, 5, 7, 8, 10, 11, 12, 19, 26, 27, 28, 29, 32], sections: ['Elemente generale', 'Ținuta rituală', 'Ținuta cu vizitatori', 'Ținuta albă'] },
    use: 'Event classification, preparation responsibilities, visitor boundaries, debates and non-ritual educational sessions.',
    review: { required: true, reason: 'Use as clarification only where it does not conflict with higher-ranked sources.' },
  },
  {
    id: 'ceremony-saint-john-summer-6024',
    document: 'Ceremonia Sf Ioan Vara versiunea 2024 IP1.pdf',
    kind: 'approved_ceremony',
    authorityTier: 'approved_guides_and_ceremonies',
    locator: { pages: [4, 5, 6, 7, 9, 10], sections: ['Precizări și recuzită', 'Ceremonia'] },
    use: 'Optional seasonal scene: solar cycle, circle, tangents, grain, water, bread and light.',
    review: { required: true, reason: 'Seasonal content must be enabled only for an approved event and reviewed configuration.' },
  },
  {
    id: 'registry-csa-6025-6026',
    document: '1. Registrul Matricol CSA 6025 - 6026.xlsx',
    kind: 'tenant_operational_model',
    authorityTier: 'tenant_legal_and_operational_records',
    locator: { sheets: [{ name: '6025 - 6026', range: 'A1:W3' }, { name: 'Prezenta', range: 'B2:V3' }, { name: 'PREZENTA 6015-6016', range: 'A1:W4', hidden: true }] },
    use: 'Field inventory for dossiers, degree and status history, offices, attendance and travel records. No row-level data is embedded here.',
    review: { required: true, reason: 'Header semantics, duplicate numbering and attendance codes require tenant validation before import.' },
  },
  {
    id: 'statute-nova-reperta-2024',
    document: 'Statut Asociația NR - 26.08.2024.docx',
    kind: 'tenant_legal_boundary',
    authorityTier: 'tenant_legal_and_operational_records',
    locator: { sections: ['Capitolul II', 'Capitolul III', 'Capitolul IV', 'Capitolul V'] },
    use: 'Public association, education, culture, volunteering and support activities; kept distinct from private degree content.',
    review: { required: true, reason: 'Only non-personal organizational rules may be used; personal identifiers are excluded.' },
  },
  {
    id: 'leadership-keys-hermeneutics',
    document: 'Cheile de Succes pentru Conducatorii Lojii Cercul de Hermeneutica.txt',
    kind: 'internal_pedagogy_transcript',
    authorityTier: 'internal_pedagogy',
    locator: { sections: ['linia de progresie', 'parcurs educativ pe grade', 'echipe de mentorat', 'analiza anuală a Loji'] },
    use: 'Personalized mentorship, degree-specific study, reflection, projects, office preparation and annual planning.',
    review: { required: true, reason: 'Informal transcript; terminology and recommendations require editorial and authorized review.' },
  },
  {
    id: 'encyclopedia-efu-a',
    document: 'EFU_lit_A.pdf',
    kind: 'historical_reference',
    authorityTier: 'reference_and_historical',
    locator: { pages: [16, 17], entries: ['Acacia'] },
    use: 'Optional historical context for a grade 3 symbol after validation; never used as normative meaning.',
    review: { required: true, reason: 'Secondary reference with interpretations that may differ from the active ritual.' },
  },
  {
    id: 'encyclopedia-efu-b1',
    document: 'EFU_lit_B1.pdf',
    kind: 'historical_reference',
    authorityTier: 'reference_and_historical',
    locator: { pages: [4, 264, 274], entries: ['Coloana de la prag', 'Biblia'] },
    use: 'Optional historical context for threshold columns and sacred-text traditions after validation.',
    review: { required: true, reason: 'Secondary reference; active ritual and constitutional sources take precedence.' },
  },
  {
    id: 'statute-mlnr-2003-historical',
    document: '00 Statutul MLNR.doc',
    kind: 'historical_governance_reference',
    authorityTier: 'reference_and_historical',
    locator: { sections: ['Art. 2-8', 'Art. 10-14'] },
    use: 'Historical context for membership, minutes, delegation, finance and registers.',
    review: { required: true, reason: 'Historical/superseded source; it must not drive current authorization or compliance.' },
  },
]);
