export const SYMBOL_CATALOG = Object.freeze([
  {
    id: 'g1-rough-stone', grade: 1, label: 'Piatra Brută', zoneId: 'north-learning-column',
    objective: 'Identifică o direcție concretă de șlefuire personală, fără comparație cu ceilalți Frați.',
    interaction: { type: 'inspect_reflect_commit', motion: 'slow_rotation', output: 'private_journal_entry' },
    prompt: 'Ce parte din lucrarea ta interioară merită atenție în perioada următoare?',
    sourceRefIds: ['ritual-apprentice-2012'], validation: { required: false },
  },
  {
    id: 'g1-plumb-axis', grade: 1, label: 'Firul cu plumb', zoneId: 'mosaic-center',
    objective: 'Explorează verticalitatea ca verificare practică între intenție, cuvânt și faptă.',
    interaction: { type: 'balance_alignment', motion: 'damped_pendulum', output: 'reflection_checkpoint' },
    prompt: 'Unde există astăzi o abatere între intenție și faptă?',
    sourceRefIds: ['ritual-apprentice-2012'], validation: { required: false },
  },
  {
    id: 'g1-mosaic-floor', grade: 1, label: 'Pavajul Mozaicat', zoneId: 'mosaic-center',
    objective: 'Observă contrastul, alternanța și echilibrul fără a le reduce la o opoziție simplistă.',
    interaction: { type: 'pattern_observation', motion: 'light_only', output: 'guided_note' },
    sourceRefIds: ['ritual-apprentice-2012'], validation: { required: true, reason: 'Pattern proportions and traversal boundary require visual validation.' },
  },
  {
    id: 'g1-three-pillars', grade: 1, label: 'Cei Trei Mari Stâlpi', zoneId: 'mosaic-center',
    objective: 'Leagă înțelepciunea, forța și frumusețea de planificare, împlinire și grija pentru formă.',
    interaction: { type: 'three_point_constellation', motion: 'sequential_light', output: 'concept_links' },
    sourceRefIds: ['ritual-apprentice-2012'], validation: { required: true, reason: 'Placement and architectural orders require authorized review.' },
  },
  {
    id: 'g1-threshold-columns', grade: 1, label: 'Coloanele Pragului', zoneId: 'lost-steps-hall',
    objective: 'Descoperă orientarea și diferența dintre apropiere, intrare și lucrare.',
    interaction: { type: 'threshold_orientation', motion: 'parallax_only', output: 'orientation_complete' },
    sourceRefIds: ['ritual-apprentice-2012', 'encyclopedia-efu-b1'], validation: { required: true, reason: 'Historical reference is contextual only; ritual placement takes precedence.' },
  },
  {
    id: 'g1-great-lights', grade: 1, label: 'Cele Trei Mari Lumini', zoneId: 'east-light',
    objective: 'Recunoaște configurația vizuală a gradului ca reper de orientare, fără conținut de jurământ sau recunoaștere.',
    interaction: { type: 'controlled_closeup', motion: 'none', output: 'observation_complete' },
    sourceRefIds: ['ritual-apprentice-2012', 'constitution-mlnr-6016'], validation: { required: true, reason: 'Exact arrangement and permitted explanation require authorized sign-off.' },
  },
  {
    id: 'g1-star-vault', grade: 1, label: 'Bolta Înstelată', zoneId: 'north-learning-column',
    objective: 'Folosește orientarea spațială și ciclurile recurente drept cadru pentru observație atentă.',
    interaction: { type: 'constellation_orientation', motion: 'slow_sky_rotation', output: 'observation_sequence' },
    sourceRefIds: ['ritual-apprentice-2012'], validation: { required: true, reason: 'Constellation placement must be checked against the supplied layout.' },
  },
  {
    id: 'g1-seasonal-circle', grade: 1, label: 'Cercul Luminii Sezoniere', zoneId: 'mosaic-center', optional: true,
    objective: 'Leagă ciclurile, moderația, recunoștința și transmiterea într-un eveniment sezonier aprobat.',
    interaction: { type: 'seasonal_light_sequence', motion: 'sequential_candles', output: 'shared_reflection' },
    sourceRefIds: ['ceremony-saint-john-summer-6024'], validation: { required: true, reason: 'Enable only in an approved event window and after configuration review.' },
  },
  {
    id: 'g2-cubic-stone', grade: 2, label: 'Piatra Cubică', zoneId: 'geometry-workbench',
    objective: 'Transformă disciplina personală într-o lucrare precisă și folositoare mai departe.',
    interaction: { type: 'construct_measure_reflect', motion: 'axis_rotation', output: 'workshop_note' },
    sourceRefIds: ['ritual-apprentice-2012', 'ritual-fellowcraft-2012'], validation: { required: false },
  },
  {
    id: 'g2-level', grade: 2, label: 'Nivela', zoneId: 'geometry-workbench',
    objective: 'Exersează judecata echilibrată prin colaborare și dialog.',
    interaction: { type: 'collaborative_balance', motion: 'damped_tilt', output: 'discussion_prompt' },
    sourceRefIds: ['ritual-fellowcraft-2012', 'regulation-general-6016'], validation: { required: false },
  },
  {
    id: 'g2-blazing-star', grade: 2, label: 'Steaua Înflăcărată', zoneId: 'concept-constellation',
    objective: 'Leagă geometria, cercetarea disciplinată și căutarea ordinii.',
    interaction: { type: 'layered_discovery', motion: 'subtle_pulse', output: 'concept_map_entry' },
    sourceRefIds: ['ritual-fellowcraft-2012'], validation: { required: true, reason: 'The explanation depth must remain grade-specific.' },
  },
  {
    id: 'g2-paired-spheres', grade: 2, label: 'Sferele Cunoașterii', zoneId: 'world-spheres',
    objective: 'Compară observarea lumii apropiate cu orientarea către întregul mai cuprinzător.',
    interaction: { type: 'paired_orbits', motion: 'independent_orbits', output: 'comparison_note' },
    sourceRefIds: ['ritual-fellowcraft-2012'], validation: { required: true, reason: 'Placement is conditional on the approved scene configuration.' },
  },
  {
    id: 'g2-five-senses', grade: 2, label: 'Cele Cinci Ferestre', zoneId: 'senses-gallery',
    objective: 'Observă cum percepția hrănește cunoașterea și unde o poate induce în eroare.',
    interaction: { type: 'five_stage_sensory_lab', motion: 'responsive_light', output: 'learning_checkpoint' },
    sourceRefIds: ['ritual-fellowcraft-2012', 'leadership-keys-hermeneutics'], validation: { required: true, reason: 'Exercises require pedagogical review and accessible alternatives.' },
  },
  {
    id: 'g2-great-lights', grade: 2, label: 'Marile Lumini - configurația gradului', zoneId: 'fellowcraft-board',
    objective: 'Observă schimbarea specifică gradului în relația dintre uneltele simbolice.',
    interaction: { type: 'controlled_closeup', motion: 'none', output: 'comparison_complete' },
    sourceRefIds: ['ritual-fellowcraft-2012'], validation: { required: true, reason: 'Exact arrangement and wording require authorized sign-off.' },
  },
  {
    id: 'g2-tracing-board', grade: 2, label: 'Planșa Calfei', zoneId: 'fellowcraft-board',
    objective: 'Parcurge o hartă atent alcătuită: de la simbol la observație, întrebare, dezbatere și aplicare.',
    interaction: { type: 'guided_symbol_map', motion: 'node_highlights', output: 'study_path_progress' },
    sourceRefIds: ['ritual-fellowcraft-2012', 'guide-meetings-6019'], validation: { required: true, reason: 'Only reviewed educational nodes may be published.' },
  },
  {
    id: 'g3-acacia', grade: 3, label: 'Ramura de Acacia', zoneId: 'memory-veil',
    objective: 'Reflectează asupra continuității, integrității și a ceea ce merită transmis.',
    interaction: { type: 'memory_constellation', motion: 'growth_points', output: 'mentor_reflection' },
    sourceRefIds: ['ritual-master-2012', 'encyclopedia-efu-a'], validation: { required: true, reason: 'Ritual meaning takes precedence; encyclopedia context requires editorial review.' },
  },
  {
    id: 'g3-circle-center', grade: 3, label: 'Centrul Cercului', zoneId: 'middle-chamber',
    objective: 'Examinează responsabilitatea dintr-un centru stabil, nu prin rang sau vizibilitate.',
    interaction: { type: 'perspective_centering', motion: 'camera_orbit', output: 'responsibility_note' },
    sourceRefIds: ['ritual-master-2012'], validation: { required: true, reason: 'Explanation must remain a reviewed paraphrase.' },
  },
  {
    id: 'g3-great-lights', grade: 3, label: 'Marile Lumini - configurația gradului', zoneId: 'master-board',
    objective: 'Observă relația specifică gradului dintre uneltele simbolice ca reper de sinteză.',
    interaction: { type: 'controlled_closeup', motion: 'none', output: 'synthesis_complete' },
    sourceRefIds: ['ritual-master-2012'], validation: { required: true, reason: 'Exact arrangement and permitted explanation require authorized sign-off.' },
  },
  {
    id: 'g3-memory-veil', grade: 3, label: 'Pragul Memoriei', zoneId: 'memory-veil',
    objective: 'Leagă lucrarea prezentă de tradiție, păstrând răspunderea critică pentru ceea ce transmiți.',
    interaction: { type: 'source_timeline', motion: 'layered_reveal', output: 'curated_timeline_note' },
    sourceRefIds: ['ritual-master-2012', 'regulation-general-6016'], validation: { required: true, reason: 'No ceremonial reenactment or restricted narrative may be delivered.' },
  },
  {
    id: 'g3-master-board', grade: 3, label: 'Planșa Maestrului', zoneId: 'master-board',
    objective: 'Sintetizează simboluri, alegeri etice, mentorat și proiecte de grup.',
    interaction: { type: 'guided_symbol_map', motion: 'node_highlights', output: 'master_study_path' },
    sourceRefIds: ['ritual-master-2012', 'guide-meetings-6019'], validation: { required: true, reason: 'Only reviewed grade 3 nodes may be published.' },
  },
  {
    id: 'g3-travel-lines', grade: 3, label: 'Liniile Călătoriei', zoneId: 'mentorship-circle',
    objective: 'Cartografiază învățarea primită, lucrarea împlinită și cunoașterea împărtășită responsabil.',
    interaction: { type: 'bidirectional_path_map', motion: 'flow_lines', output: 'mentorship_plan' },
    sourceRefIds: ['ritual-master-2012', 'leadership-keys-hermeneutics'], validation: { required: true, reason: 'Mentorship model requires tenant pedagogical approval.' },
  },
]);
