server {
  listen 80 default_server;
  server_name _;
  server_tokens off;
  client_max_body_size 50m;

  location = /healthz {
    access_log off;
    return 200 "ok\n";
  }

  location ~ ^/portal(/.*|$) {
    alias /var/meteor/csa-build/bundle/public$1;
    passenger_base_uri /portal;
    passenger_app_root /var/meteor/csa-build/bundle;
    passenger_document_root /var/meteor/csa-build/bundle/public;
    passenger_enabled on;
    passenger_app_type node;
    passenger_startup_file main.js;
    passenger_nodejs /usr/local/bin/csa-node;
    passenger_app_env production;
    passenger_min_instances 1;
    passenger_start_timeout 300;
    passenger_max_request_queue_size 100;
  }
}
