server {
  listen 80 default_server;
  server_name _;
  client_max_body_size 50m;

  root /var/meteor/csa-build/bundle/public;
  passenger_enabled on;
  passenger_app_type node;
  passenger_startup_file main.js;
  passenger_nodejs /usr/local/bin/csa-node;
  passenger_app_env production;
  passenger_min_instances 1;
  passenger_start_timeout 300;
  passenger_max_request_queue_size 100;
}
