// Server-only pedagogical commentary. These are study proposals, not ritual quotations.
const NOTES = {
  'grand-master-seat': ['Reperează scaunul rezervat la dreapta Venerabilului și deosebește orientarea celui așezat de privirea dinspre intrare.', 'Compară locul rezervat Marelui Maestru cu celelalte locuri de la Orient și observă ordinea primirii oaspeților.', 'Examinează continuitatea protocolului și diferența dintre conducerea Lojei și prezența unui demnitar al Marii Loji.'],
  'rough-stone': ['Observă fețele neregulate ale pietrei și identifică rolul pregătirii înainte de prima intervenție.', 'Compară forma brută cu forma cubică și leagă schimbarea de alegerea și folosirea metodică a uneltelor.', 'Reflectează la felul în care poți îndruma începutul unei lucrări fără să înlocuiești experiența celui care o execută.'],
  'cubic-stone': ['Compară regularitatea fețelor și unghiurilor cu forma pietrei brute, fără a confunda finisarea cu lipsa oricărei imperfecțiuni.', 'Observă cubul și vârful piramidal descris pe Tabloul Calfei; separă proprietățile geometrice de interpretarea personală.', 'Examinează cum se verifică și se integrează o piesă finisată într-o construcție comună durabilă.'],
  mallet: ['Recunoaște capul și mânerul ciocanului de lucru și raportul său cu Dalta de lângă Altar.', 'Compară efortul repetat cu precizia intervenției, punând Ciocanul în relație cu măsura și verificarea.', 'Examinează felul în care transmiți folosirea responsabilă a forței, cu atenție față de lucrare și participant.'],
  chisel: ['Identifică muchia Daltei și observă cum un instrument precis dirijează efortul ciocanului de lucru.', 'Leagă intervenția punctuală de planul întregii lucrări; verifică înainte de a îndepărta material.', 'Reflectează asupra îndrumării atente: o corecție utilă cere precizie și respect față de lucrarea celuilalt.'],
  ruler: ['', 'Compară lungimile și gradațiile Riglei; distinge o măsurare verificabilă de o impresie aproximativă.', 'Examinează Rigla în contextul planșei Maestrului, păstrând diferența dintre unealta de studiu și narațiunea gradului.'],
  lever: ['', 'Observă relația dintre sprijin, efort și deplasare; pune eficiența Levierului în legătură cu alegerea metodei.', 'Studiază locul Levierului în Tabloul Camerei de Mijloc și responsabilitatea asociată utilizării unui instrument.'],
  'working-square': ['', 'Verifică unghiul drept dintre brațele Echerului și compară forma acestuia cu echerul de pe Altar.', 'Pune corectitudinea măsurii în relație cu asumarea unei lucrări comune și cu explicarea clară a criteriilor ei.'],
  'working-compass': ['', 'Observă articulația și cele două brațe ale Compasului; leagă deschiderea lui de măsura și proporția lucrării.', 'Examinează relația dintre limite, proporție și transmiterea metodei, în contextul planșei proprii gradului.'],
  wheat: ['', 'Identifică spicul lângă Jachin și folosește creșterea treptată drept punct de pornire pentru reflecția asupra învățării.', ''],
  acacia: ['', '', 'Privește ramura în contextul planșei Maestrului și reflectează asupra continuității și a responsabilității transmiterii.'],
  trowel: ['', '', 'Ca exercițiu suplimentar, observă lama și mânerul mistriei; gândește finisarea și legătura dintre părțile lucrării, fără a atribui exercițiul ritualului.'],
  wisdom: ['Recunoaște volutele ionice și leagă Înțelepciunea de pregătirea atentă a lucrării.', 'Compară rolul planificării, sugerat de coloneta ionică, cu realizarea și forma lucrării, reprezentate de ceilalți doi stâlpi.', 'Examinează cum poți transmite discernământul: explică alegerea unei direcții și asumă consecințele ei.'],
  strength: ['Observă simplitatea colonetei dorice și folosește-o ca punct de pornire pentru studiul perseverenței.', 'Raportează Forța la o lucrare susținută prin metodă și colaborare, nu numai prin efort individual.', 'Examinează felul în care autoritatea susține continuitatea lucrării fără a înlocui judecata celorlalți.'],
  beauty: ['Identifică frunzele de acant și observă grija pentru detaliu a colonetei corintice.', 'Compară proporțiile și ornamentul: când contribuie forma la calitatea unei lucrări?', 'Gândește Frumusețea ca grijă pentru ansamblul transmis, de la realizare la felul în care este explicat altora.'],
  sun: ['Localizează Soarele la Orient, spre Miazăzi, și distinge-l de Luna aflată pe cealaltă parte.', 'Compară cele două luminare prin formă, poziție și mod de reprezentare; construiește o explicație bazată pe observație.', 'Pregătește o prezentare a Orientului care pune Soarele în relație cu Luna și Delta, fără a confunda observația cu interpretarea.'],
  moon: ['Recunoaște semiluna în creștere și poziția ei deasupra locului Secretarului.', 'Compară schimbarea sugerată de faza Lunii cu forma constantă a discului solar reprezentat în templu.', 'Explică unui participant cum se poate studia un simbol al schimbării fără a-i atribui automat o singură interpretare.'],
  delta: ['Observă triunghiul și ochiul central. Pornește reflecția de la atenția asupra propriilor fapte.', 'Compară centrul, simetria și limitele figurii; distinge ceea ce vezi de explicațiile pe care le propui.', 'Examinează responsabilitatea unei priviri de ansamblu și felul în care poți transmite simbolul fără a impune o lectură unică.'],
  mosaic: ['Observă alternanța pătratelor și delimitează pavajul de căile de circulație. Respectă spațiul central.', 'Studiază raporturile dintre laturi și pătrate, apoi leagă contrastul de relația dintre părțile unei lucrări.', 'Privește pavajul ca parte a întregii Camere de Mijloc; explică de ce respectarea spațiului comun rămâne importantă.'],
  border: ['Identifică marginea pavajului și traseul liber din jurul lui.', 'Compară interiorul și exteriorul conturului: cum organizează limita circulația și proporțiile?', 'Analizează cum poate o limită comună să protejeze lucrarea fără să devină un obstacol pentru înțelegere.'],
  plumb: ['Urmărește verticala dintre boltă și centrul pavajului. Folosește-o ca exercițiu de atenție și aliniere personală.', 'Pune verticalitatea în relație cu măsura și echilibrul lucrării; verifică o abatere înainte de a o corecta.', 'Examinează consecvența dintre principiile pe care le transmiți și exemplul pe care îl oferi.'],
  vault: ['Ridică privirea spre boltă și identifică cele două grupe de coloane laterale.', 'Leagă semnele zodiacale, coloanele și orientarea sălii într-o hartă coerentă, distingând decorul de o hartă astronomică.', 'Pregătește o explicație a ansamblului care păstrează relațiile dintre repere și limitele reprezentării digitale.'],
  rope: ['Urmărește continuitatea funiei și recunoaște nodurile și ciucurii de la intrare.', 'Compară rolul fiecărui nod cu continuitatea întregii legături; propune un exemplu de cooperare.', 'Examinează ce responsabilități mențin legătura dintre generații și cum poate fi păstrată încrederea.'],
  orient: ['Localizează intrarea, Orientul și treptele înainte de a numi funcțiile aflate acolo.', 'Corelează axa Orient–Occident cu poziția altarului și a reperelor proprii scenei deschise.', 'Analizează organizarea ansamblului și responsabilitatea celor care coordonează lucrarea din Orient.'],
  altar: ['Identifică cele Trei Mari Lumini și observă configurația uneltelor descrisă pentru gradul tău.', 'Compară configurația uneltelor din scena Calfei cu cea deja cunoscută și formulează diferența precis.', 'Examinează configurația Camerei de Mijloc și modul în care o explici păstrând limitele de acces ale participanților.'],
  book: ['Observă cartea deschisă și regula așezării alături a volumelor diferitelor religii.', 'Studiază relația dintre un reper de sens și uneltele de măsură așezate pe el, respectând pluralitatea convingerilor.', 'Reflectează asupra responsabilității de a păstra atât un cadru comun, cât și respectul pentru convingerile individuale.'],
  square: ['Recunoaște Echerul și poziția lui în configurația Ucenicului; pornește de la ideea verificării unei direcții.', 'Observă relația Echerului cu cele două brațe ale Compasului în configurația Calfei.', 'Explică relația Echerului cu Compasul în configurația Maestrului și leagă verificarea de răspunderea personală.'],
  compass: ['Identifică Compasul între Marile Lumini și studiază noțiunea de măsură, pornind de la forma lui.', 'Urmărește diferența dintre cele două brațe în configurația Calfei și compară atent cu configurația cunoscută.', 'Studiază configurația Maestrului ca ansamblu și discută cum stabilești limite juste într-o responsabilitate asumată.'],
  board: ['Găsește planșa Ucenicului între cei trei stâlpi și numește reperele pe care le-ai identificat în sală.', 'Folosește planșa Calfei pentru a construi relații între repere, proporții și întrebările de studiu.', 'Folosește planșa Maestrului ca suport pentru sinteză și transmitere, adaptând explicațiile destinatarului.'],
  column: ['Recunoaște poziția coloanei la intrare și rodiile capitelului; deosebește coloana arhitecturală de rândurile de scaune numite tot coloane.', 'Leagă coloana de sfera așezată pe capitel și compară perechea de la intrare fără a confunda cele două reprezentări.', 'Prezintă rolul perechii de coloane în orientarea templului, distingând arhitectura comună de configurațiile specifice scenelor.'],
  globe: ['', 'Compară ceea ce reprezintă această sferă cu sfera de pe coloana opusă: lumea apropiată și orientarea cerească.', 'Explică diferența dintre cele două sfere și caracterul lor convențional în modelul digital, păstrând contextul sursei.'],
  candles: ['Numără lumânările acestui sfeșnic și identifică funcția de la masa lui.', 'Compară acest sfeșnic cu celelalte două mese și cu lumânările colonetelor; observă gruparea luminilor.', 'Explică ansamblul luminilor ca parte a organizării lucrării, păstrând distincte sfeșnicele meselor și cei trei stâlpi.'],
  gavel: ['Identifică ciocanul ca obiect al funcției, asociat cu ordinea și acordarea cuvântului.', 'Observă cum contribuie semnalele conducerii la coordonarea participanților și la disciplina dialogului.', 'Reflectează asupra exercitării autorității cu măsură și a răspunderii pentru desfășurarea lucrării.'],
  sword: ['Recunoaște spada de la Orient și locul ei între obiectele Maestrului Venerabil.', 'Compară funcția acestui obiect cu celelalte instrumente ale conducerii, păstrând contextul amplasării.', 'Examinează responsabilitatea asociată obiectelor funcției și felul în care distingi autoritatea de persoana care o exercită.'],
  star: ['', 'Observă cele cinci vârfuri, centrul și proporțiile Stelei din fața altarului. Pune forma în relație cu studiul geometriei.', ''],
  'tyler-sword': ['Identifică spada verticală lângă locul Acoperitorului și leag-o de păstrarea pragului.', 'Pune grija pentru prag în relație cu buna desfășurare a lucrărilor de Calfă, fără a confunda simbolul cu o procedură de acces.', 'Examinează răspunderea păstrării cadrului lucrării și a accesului potrivit gradului, în coordonare cu ofițerii.'],
  'expert-sword': ['Recunoaște spada Expertului lângă locul său și deosebește-o de spada Acoperitorului.', 'Compară responsabilitatea pregătirii rituale cu cea a păstrării pragului: funcțiile cooperează, dar au sarcini distincte.', 'Reflectează asupra transmiterii corecte a instruirii și asupra verificării pregătirii fără improvizații.'],
  'mc-staff': ['Identifică bastonul lângă scaunul Maestrului de Ceremonii, în zona Occidentului.', 'Urmărește legătura dintre orientarea în spațiu, coordonarea deplasărilor și ordinea unei lucrări comune.', 'Pregătește o explicație despre coordonarea discretă și continuitatea ceremonialului, potrivită participanților.'],
};

const OFFICES = {
  venerable: ['Identifică locul de la Orient și rolul de conducere a lucrărilor.', 'Observă relația dintre conducerea lucrării, ordinea intervențiilor și sprijinul celor doi Supraveghetori.', 'Examinează răspunderea conducerii: pregătire, discernământ, continuitate și respectarea cadrului comun.'],
  first_warden: ['Localizează Primul Supraveghetor la Occident și deosebește-i locul de cel al celui de-al Doilea Supraveghetor.', 'Leagă funcția Primului Supraveghetor de îndrumarea lucrului Calfelor și de progresul prin studiu și colaborare.', 'Examinează cum susține îndrumarea Calfelor formarea unei lucrări autonome și responsabile.'],
  second_warden: ['Leagă funcția celui de-al Doilea Supraveghetor de îndrumarea Ucenicilor și localizează-i locul la Miazăzi.', 'Compară îndrumarea de început cu aprofundarea prin lucru: sprijinul pedagogic se adaptează nivelului participantului.', 'Examinează responsabilitatea formării Ucenicilor și a păstrării unui cadru în care întrebările primesc răspunsuri potrivite.'],
  secretary: ['Recunoaște locul Secretarului și rolul consemnării și păstrării documentelor Lojei.', 'Leagă studiul și contribuția proprie de o consemnare clară: sursă, dată și context.', 'Examinează continuitatea arhivei, exactitatea evidențelor și responsabilitatea transmiterii lor.'],
  orator: ['Identifică Oratorul și rolul urmăririi respectării cadrului lucrărilor.', 'Distinge o opinie argumentată de o concluzie formulată în raport cu regulile comune.', 'Analizează răspunderea formulării concluziilor și păstrării legalității lucrărilor.'],
  treasurer: ['Recunoaște locul Trezorierului și deosebește gestiunea resurselor de activitatea Ospitalierului.', 'Leagă contribuția la o lucrare comună de măsură, evidență și folosirea justificată a resurselor.', 'Examinează responsabilitatea gestiunii, verificării și raportării, fără a confunda funcția cu un drept personal asupra resurselor.'],
  hospitalier: ['Recunoaște locul Ospitalierului și rolul sprijinului fratern oferit cu discreție.', 'Reflectează la felul în care observi o nevoie și contribui util, respectând demnitatea celui sprijinit.', 'Examinează continuitatea sprijinului, confidențialitatea și răspunderea față de resursele destinate ajutorării.'],
  expert: ['Localizează Expertul lângă Ospitalier și recunoaște rolul pregătirii și instruirii ritualice.', 'Pune întrebările de studiu în relație cu verificarea sursei și cu pregătirea atentă a lucrării.', 'Examinează responsabilitatea instruirii, verificării și transmiterii fidele a practicii gradului.'],
  tyler: ['Localizează Acoperitorul lângă intrare și recunoaște grija pentru pragul interior.', 'Leagă păstrarea pragului de cadrul de lucru rezervat participanților autorizați ai scenei Calfei.', 'Examinează coordonarea cu ceilalți ofițeri pentru păstrarea cadrului Camerei de Mijloc.'],
  master_of_ceremonies: ['Localizează Maestrul de Ceremonii și bastonul său; observă rolul orientării participanților.', 'Leagă pregătirea spațiului de coordonarea ordonată a participanților și de continuitatea lucrării.', 'Examinează cum se pregătește și se transmite coordonarea ceremonialului, astfel încât fiecare rol să rămână clar.'],
};

export function studyForElement(key, grade, label) {
  let family = key;
  let notes;
  if (key.startsWith('office-')) notes = OFFICES[key.slice(7)];
  else {
    if (key.startsWith('column-')) family = 'column';
    if (key.startsWith('globe-')) family = 'globe';
    if (key.startsWith('candles-')) family = 'candles';
    if (key.startsWith('gavel-')) family = 'gavel';
    notes = NOTES[family];
  }
  if (key.startsWith('zodiac-')) notes = [
    `Localizează ${label} și coloana sa laterală. Numește latura și vecinii medalionului.`,
    `Așază ${label} în succesiunea semnelor de pe aceeași latură și compară organizarea cu latura opusă.`,
    `Prezintă locul reperului ${label} în ansamblul bolții, distingând dispunerea documentată de convenția vizuală a aplicației.`,
  ];
  if (key === 'seating-north') notes = ['La lucrările de gradul I, aici este coloana Ucenicilor. Locurile primului rând sunt rezervate conform regulilor de așezare; Maeștrii se pot așeza pe ambele laturi.', 'În Loja Calfelor nu participă Ucenici. Latura de Miazănoapte rămâne parte a sălii; denumirea istorică a coloanei nu înseamnă că aici sunt prezenți Ucenici.', 'În Camera de Mijloc participă numai Maeștri. Locurile de la Miazănoapte sunt citite în acest context, fără a le eticheta drept locuri ocupate de Ucenici.'];
  if (key === 'seating-south') notes = ['La lucrările de gradul I, Calfele se așază la Miazăzi, în spatele celui de-al Doilea Supraveghetor, respectând regula primului rând. Maeștrii se pot așeza pe ambele laturi.', 'La Miazăzi se află coloana Calfelor. La lucrările acestui grad participă Calfe și Maeștri; regula așezării se păstrează.', 'În Camera de Mijloc participă numai Maeștri. Locurile de la Miazăzi sunt astfel prezentate ca locuri ale Maeștrilor, nu ca o coloană de Calfe prezente.'];
  const body = notes?.[grade - 1];
  if (!body) throw new Error(`Missing degree study: ${key} / ${grade}`);
  return { title: `Studiu propus · ${{1:'Ucenic',2:'Calfă',3:'Maestru'}[grade]}`, body };
}
